### ISSUE TITLE
Upgrades to tactic client lib

### ISSUE THREAD

**Issue by MagicRedDeer** [rvanlaar/tactic-client#1]
The tactic project is now being developed actively. Upgraded to support python 3 and has had numerous alpha, beta and release versions. Please update this pip package upto version 4.8+. 

Many thanks

**Comment by rvanlaar** [comment]
Hi,

Thank you for the PR. I've looked into the changes.

One thing I noticed is that the git commit messages from TACTIC weren't included. That's something I tried to keep intact when I first released this client.

I've switched the package over to use git submodules with two reasons in mind:
- Give users assurances that the code is from Southpaw without changes
- Makes it more easy to update the code in the future.

I would like to make sure it all works now.
This is all uploaded to pypi with as 4.8.dev0. Could you give that for a spin?
The code for this is on the branch submodules.

- Roland

**Comment by MagicRedDeer** [comment]
`TacticServerStub` from the `4.8.dev0` pip package works as expected in a python 3.7.9 virtualenv with [the docker image](https://hub.docker.com/r/diegocortassa/tactic).

There is only one problem that the scripts don't come with a "shebang" and that causes bash to throw errors.

The [code](https://github.com/rvanlaar/tactic-client/blob/f45ee7fce9d59805f9ca1c026d3fba880fd4a9d6/setup.py#L32) seems to have a `bin/` missing, but the scripts are there in the bin directory.

**Comment by MagicRedDeer** [comment]
The submodule with the symlinks seems to be a good idea because of the reasons you mentioned.  

Cheers.

**Comment by rvanlaar** [comment]
I've updated the setup.py with the 'bin/'.

About the shebang: My idea would be to create a PR with tactic to add the shebang in there.
What are your thoughts?

**Comment by rvanlaar** [comment]
Note to self: Description for the project on pypi is empty on the new release.

**Comment by MagicRedDeer** [comment]
https://github.com/Southpaw-TACTIC/TACTIC/pull/1693

accepted!

**Comment by rvanlaar** [comment]
That's great news. 
It seems a new version, 4.9 was released, however it didn't include your patches.

**Comment by rvanlaar** [comment]
Thank you for your work. The submodule branch is now merged with master and the latest 4.8 branch has been released on pypi.

**Comment by rvanlaar** [comment]
Issue is resolved. @MagicRedDeer please comment if there are still open items related to this issue.
